package com.example.crudbase.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(description = "Client returned by the API")
public class ClienteResponseDTO {

    @Schema(description = "Unique identifier generated by the server", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;

    @Schema(description = "Client's first name", example = "Juan")
    private String firstName;

    @Schema(description = "Client's last name", example = "Fernandez")
    private String lastName;

    @Schema(description = "Client's email address", example = "juan.fernandez@example.com")
    private String email;

    @Schema(description = "Client's contact phone number", example = "+34600123456")
    private String phone;

    @Schema(description = "Client's postal address", example = "Calle Mayor 1, Madrid")
    private String address;

    @Schema(description = "Timestamp the client was created, set by the server", example = "2026-02-05T10:15:30Z", accessMode = Schema.AccessMode.READ_ONLY)
    private Instant createdAt;
}
