package com.example.crudbase.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.time.LocalDate;

@Schema(description = "Match result returned by the API")
public class ResultResponseDTO {

    @Schema(description = "Unique identifier generated by the server", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;

    @Schema(description = "Name of the home team", example = "Real Madrid")
    private String homeTeam;

    @Schema(description = "Name of the away team", example = "Barcelona")
    private String awayTeam;

    @Schema(description = "Goals scored by the home team", example = "2")
    private Integer homeScore;

    @Schema(description = "Goals scored by the away team", example = "1")
    private Integer awayScore;

    @Schema(description = "Date the match was played", example = "2026-02-05")
    private LocalDate matchDate;

    @Schema(description = "Competition or tournament the match belongs to", example = "La Liga")
    private String competition;

    @Schema(description = "Venue where the match was played", example = "Santiago Bernabeu")
    private String venue;

    public ResultResponseDTO() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHomeTeam() {
        return homeTeam;
    }

    public void setHomeTeam(String homeTeam) {
        this.homeTeam = homeTeam;
    }

    public String getAwayTeam() {
        return awayTeam;
    }

    public void setAwayTeam(String awayTeam) {
        this.awayTeam = awayTeam;
    }

    public Integer getHomeScore() {
        return homeScore;
    }

    public void setHomeScore(Integer homeScore) {
        this.homeScore = homeScore;
    }

    public Integer getAwayScore() {
        return awayScore;
    }

    public void setAwayScore(Integer awayScore) {
        this.awayScore = awayScore;
    }

    public LocalDate getMatchDate() {
        return matchDate;
    }

    public void setMatchDate(LocalDate matchDate) {
        this.matchDate = matchDate;
    }

    public String getCompetition() {
        return competition;
    }

    public void setCompetition(String competition) {
        this.competition = competition;
    }

    public String getVenue() {
        return venue;
    }

    public void setVenue(String venue) {
        this.venue = venue;
    }
}
