package com.example.crudbase.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(description = "Match result returned by the API")
public class ResultResponseDTO {

    @Schema(description = "Unique identifier generated by the server", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;

    @Schema(description = "Name of the home team", example = "Real Madrid")
    private String homeTeam;

    @Schema(description = "Name of the away team", example = "Barcelona")
    private String awayTeam;

    @Schema(description = "Goals scored by the home team", example = "2")
    private Integer homeScore;

    @Schema(description = "Goals scored by the away team", example = "1")
    private Integer awayScore;

    @Schema(description = "Date the match was played", example = "2026-02-05")
    private LocalDate matchDate;

    @Schema(description = "Competition or tournament the match belongs to", example = "La Liga")
    private String competition;

    @Schema(description = "Venue where the match was played", example = "Santiago Bernabeu")
    private String venue;
}
